{% set name = "tifftools" %}
{% set version = "1.6.1" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: 3881708fffdd031bfaaf580f9a16fd8d7af84b6ccfd72f0b0c6c10dd0d157681

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - tifftools = tifftools:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
    - importlib-metadata
  run:
    - python >={{ python_min }}
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - tifftools

about:
  home: https://github.com/DigitalSlideArchive/tifftools
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pure Python tools for reading and writing all TIFF IFDs, sub-IFDs, and tags.
  description: |
    Pure Python tools for reading and writing all TIFF IFDs, sub-IFDs, and tags. Developed by Kitware, Inc. with funding from The National Cancer Institute.
  doc_url: https://github.com/DigitalSlideArchive/tifftools/blob/master/README.rst
  dev_url: https://github.com/DigitalSlideArchive/tifftools

extra:
  recipe-maintainers:
    - banesullivan
    - manthey
