{% set name = "tifftools" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: 083d4a320783fd3f7c279edbf5299c00767dfee4c6c98c45bfff3ca758a53be4

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - tifftools = tifftools:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
    - importlib-metadata
  run:
    - python >=3.8
    - setuptools

test:
  imports:
    - tifftools

about:
  home: https://github.com/DigitalSlideArchive/tifftools
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pure Python tools for reading and writing all TIFF IFDs, sub-IFDs, and tags.
  description: |
    Pure Python tools for reading and writing all TIFF IFDs, sub-IFDs, and tags. Developed by Kitware, Inc. with funding from The National Cancer Institute.
  doc_url: https://github.com/DigitalSlideArchive/tifftools/blob/master/README.rst
  dev_url: https://github.com/DigitalSlideArchive/tifftools

extra:
  recipe-maintainers:
    - banesullivan
    - manthey
