{% set name = "tifftools" %}
{% set version = "1.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: 4868f97988c7cd40abce164b11425aa32e2bce3ef1a746727f78ab717a357079

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - tifftools = tifftools:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
    - importlib-metadata
  run:
    - python >=3.6
    - setuptools

test:
  imports:
    - tifftools

about:
  home: https://github.com/DigitalSlideArchive/tifftools
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pure Python tools for reading and writing all TIFF IFDs, sub-IFDs, and tags.
  description: |
    Pure Python tools for reading and writing all TIFF IFDs, sub-IFDs, and tags. Developed by Kitware, Inc. with funding from The National Cancer Institute.
  doc_url: https://github.com/DigitalSlideArchive/tifftools/blob/master/README.rst
  dev_url: https://github.com/DigitalSlideArchive/tifftools

extra:
  recipe-maintainers:
    - banesullivan
    - manthey
